Cargo.lock, src/lib.rs
@cakebaker as you suggested, it is indeed much better this way :)
=> Reverse the two functions

Cargo.lock, Cargo.toml
This PR adapts the `chrono` settings in `Cargo.toml` so that the `time` crate is no longer needed.
Closes #13
=> Adapt chrono settings to remove old time crate

Cargo.lock
This PR downgrades `libc` from `0.2.145` to `0.2.144` because `0.2.145` fails in `coreutils` CICD due to https://github.com/rust-lang/libc/issues/3264
=> Downgrade libc from 0.2.145 to 0.2.144

README.md, src/lib.rs, src/parse_datetime.rs
Moving PR from main coreutils to this crate, after discussion here: https://github.com/uutils/coreutils/pull/4917
Add a relaxed datetime parser. This datetime parser functions by using `chrono`s own parsing utilities and a try/succeed approach to parsing.
This implementation of the datetime parser has some drawbacks and some positives. On the positive side:
- it was easy to implement
- it is easy to add more datetime formats to
In order to add additionally supported formats, a developer can add the required format string to the `format` mod in `parse_datetime.rs`, and then add it as a potential format to the relevant `fmts` vec.
On the negative:
- It is not easily customiseable beyond the supported `chrono` parsing formats. E.g., `chrono` does not currently support parsing offsets without …
=> add datetime parser

src/parse_datetime.rs
Add test to verify epoch seconds can be parsed by `parse_datetime`.
=> Add test for parsing epoch seconds

src/parse_datetime.rs
This PR replaces the use of the deprecated `timestamp()` with `timestamp_opt()`.
=> Use timestamp_opt() instead of timestamp() in test

Cargo.lock, Cargo.toml, src/lib.rs, src/parse_relative_time.rs, src/parse_timestamp.rs
This commit resolves #40.
Adds new file and functions parse_timestamp.
Adds tests for handling negative numbers.
@tertsdiepraam @sylvestre
=> Fixes Negative numbers for @ not being recognized

Cargo.lock, Cargo.toml, src/lib.rs, src/parse_relative_time.rs, src/parse_weekday.rs
@tertsdiepraam @cakebaker @sylvestre 
This commit resolves issue #23.
Adds parse_weekday function that uses chrono weekday parser with a map for edge cases. Adds tests cases to make sure it works correctly.
=> Support weekdays in parse_datetime

.github/workflows/ci.yml
This PR replaces the unmaintained `action-rs/toolchain` with `dtolnay/rust-toolchain` go get rid of some CI warnings. See https://github.com/actions-rs/toolchain/issues/221 for a discussion.
=> ci: use dtolnay/rust-toolchain instead of action_rs/toolchain

.github/workflows/ci.yml
This PR removes the unmaintained `actions-rs/cargo` and replaces it with direct invocations of `cargo`. It should get rid of the "The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/cargo@v1" warnings.
=> ci: remove actions-rs/cargo & use cargo directly

src/lib.rs, src/parse_time_only_str.rs
Hi, i was trying to fix the `date-sec` test case in [gnu test coverage](https://uutils.github.io/coreutils/book/test_coverage.html) in coreutils-date and i figured if i could make parse_datetime to take strings with only time and offset it would fix the issue and from the code I figured you guys are already working on a parser but as a temporary fix i wrote the following code to deal with the issue. Please do let me know if this not the way it was supposed to be implemented or any kind of change at all. Thank you
=> support for parsing date string with only time

src/lib.rs, src/parse_time_only_str.rs
This PR fixes clippy warnings from the [zero_prefixed_literal](https://rust-lang.github.io/rust-clippy/master/index.html#/zero_prefixed_literal) and [bool_assert_comparison](https://rust-lang.github.io/rust-clippy/master/index.html#/bool_assert_comparison) lints.
=> clippy: fix warnings

src/lib.rs
=> epoch timezone fix

.github/workflows/ci.yml, src/lib.rs
This PR adds `--all-targets` to the clippy job in the CI and fixes two warnings from the [zero_prefixed_literal](https://rust-lang.github.io/rust-clippy/master/index.html#/zero_prefixed_literal) lint.
=> ci: use `clippy --all-targets`

src/lib.rs
Fixes https://github.com/uutils/coreutils/issues/6392
=> Fix single digit date parsing

Cargo.lock, Cargo.toml, src/lib.rs
This PR bumps `chrono` from `0.4.26` to `0.4.38` and `iana-time-zone` from `0.1.56` to `0.1.60`. The latter is updated to avoid  having two versions of some dependencies it has in common with `chrono`. The PR also replaces the use of the deprecated `NaiveDateTime::from_timestamp_opt()` with `DateTime::from_timestamp()`.
=> Bump `chrono` and `iana-time-zone`; fix use of deprecated function

src/lib.rs, src/parse_relative_time.rs
This PR closes https://github.com/uutils/coreutils/issues/6629.
There were two problems with `parse_relative_time`, which have been fixed by this PR.
One problem was that [`parse_relative_time()`](https://github.com/uutils/parse_datetime/blob/main/src/parse_relative_time.rs#L43) got the current date using `Utc::now().date_naive()` while [`parse_relative_time_at_date()`](https://github.com/uutils/parse_datetime/blob/main/src/parse_relative_time.rs#L142) got the current date using `Local::now().date_naive()`. This means that the date in the end result will be 1 day off if the date in your timezone is different from the date in UTC.
Another problem was that [`parse_relative_time_at_date()`](https://github.com/uutils/parse_datetime/blob/main/src/parse_relative_time.rs#L107-L120) created a …
=> Don't use Durations for calculating relative times

src/parse_relative_time.rs
=> `parse_relative_time`: Include 'this' direction

fuzz/Cargo.lock
I forgot this update in https://github.com/uutils/parse_datetime/pull/74
=> Bump `iana-time-zone` in `fuzz` from `0.1.56` to `0.1.61`

src/lib.rs
This PR fixes a warning from the [needless_return](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return) lint.
=> clippy: fix warning from `needless_return` lint

src/parse_time_only_str.rs
=> Add support for military time zones

src/lib.rs
Add parsing for timezone offsets of the form +N or -N. As a side effect of this change, parsing timezone offsets like +0700, UTC+2, and Z-1 are now supported.
=> Parse single digit timezone offsets

README.md
I forgot to bump the version info in the readme when I did the release.
=> readme: bump version to 0.6.0

src/lib.rs
This is described in https://www.gnu.org/software/coreutils/manual/html_node/Calendar-date-items.html
=> Parse calendar dates with slashes, like 2/29/1996

src/parse_relative_time.rs
Change the behavior of `parse_relative_time_at_date()` so that adding months to a given date causes surplus days to overflow to the next month. For example, adding 1 month to 1996-03-31 would be 1996-04-31, but April only has 30 days, so the surplus day rolls over to the next month, resulting in 1996-05-01.
Closes #98
=> Overflow surplus days when adding months to a date

src/lib.rs
Parse a datetime with T separator between date and time, a single digit timezone offset, and no space between the time and the offset.
This is an improvement to #102, which was not able to parse the T separator.
=> Parse datetime with T separator and single digit offset

Cargo.lock, Cargo.toml, src/parse_timestamp.rs, src/parse_weekday.rs
This PR bumps `nom` from `7.1.3` to `8.0.0` and adapts the code to API changes in `nom`.
=> Bump `nom` & adapt to API changes

src/parse_relative_time.rs
Protect against a situation where adding one month to the current day would cause an overflow in the next month in some unit tests of `parse_relative_time`. For example, adding one month to March 31 should overflow to May 1 because April only has 30 days. This is a difference in the behavior we want for our library compared with the behavior of `chrono`.
This change was extracted from pull request #110.
=> Make tests of adding months more resilient

src/lib.rs
Explicitly set the timezone to `UTC0` in one of the tests of `parse_datetime`.
This change was extracted from pull request #110.
=> Explicitly set timezone UTC0 in a unit test

src/parse_relative_time.rs
Allow the empty string when parsing the relative time in `parse_relative_time_at_date()`. The empty string represents zero time delta.
This change was extracted from pull request #110.
=> Allow empty string in parse_relative_time_at_date

src/lib.rs
Simulate greedy parsing of an absolute datetime in the prefix of a
string before parsing a subsequent time delta in the suffix of the
string. This does not change the behavior of `parse_datetime`, it just
prepares the code for a future change that allows parsing both the
absolute datetime and the time delta from the same string.
Greedy parsing is implemented by iterating over a list of patterns in
decreasing order of length so that longer patterns are tried before
shorter patterns. This guarantees that if there is an absolute datetime
present at the beginning of the string, then it will definitely be
parsed and the remaining part of the string is assumed to contain a time
delta.
These changes were extracted from pull request #110.
=> Greedy parsing of datetime before time delta

fuzz/Cargo.lock, fuzz/Cargo.toml
This PR removes the unused `rand` dependency.
=> fuzz: remove `rand` dependency

src/lib.rs
Change the way dates without times are parsed by just parsing the date as-is and applying the placeholder time (00:00:00) after parsing instead of before. The previous implementation would fail to support parsing strings like "1776-07-04 +250 years".
=> Add time to parsed date after parsing not before

src/lib.rs
Change the `parse_datetime()` function so that it parses both a
reference date and a time delta from one string. The new implementation
attempts to parse the datetime from the longest possible prefix of the
string. The remainder of the string is parsed as the time delta. This
allows us to parse more combinations of reference dates and time deltas
more easily.
Fixes #104
=> Parse reference datetime and timedelta from the same string

src/parse_relative_time.rs
Fixes the issue in this comment: https://github.com/uutils/parse_datetime/issues/127#issuecomment-2741586704
Basically, something like `now +1 hour` worked, but `now + 1 hour` did not (note space after `+`).
=> Allow spaces between +/- and number

Cargo.lock, Cargo.toml, src/parse_relative_time.rs
Fixes https://github.com/uutils/parse_datetime/issues/127 and https://github.com/uutils/coreutils/issues/7662. Enables GNU test `tests/date/date-next-dow.pl` to pass:
```
$ bash util/run-gnu-test.sh tests/date/date-next-dow.pl
...
PASS: tests/date/date-next-dow.pl
============================================================================
Testsuite summary for GNU coreutils 9.6-dirty
============================================================================
============================================================================
```
Note, this also allows some formats that GNU date doesn't accept, but I think they're reasonable:
```
$ date +"%a %F"
Mon 2025-04-21
$ set d "1 monday ago" ; date -d $d +"%a %F" ; cargo run -q date -d $d +"%a %F"
date: invalid date ‘1 monday ago’
Mon …
```
=> Parse relative weekdays like "next monday"

src/items/time.rs
This PR fixes a warning from the [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) lint.
=> clippy: fix warning from `uninlined_format_args`

src/items/mod.rs, src/items/primitive.rs, src/items/time.rs, tests/time.rs
Closes #165 .
Support nanoseconds and float numbers with comma as separator.
=> feat: support nanoseconds

src/items/mod.rs, src/items/time.rs, src/lib.rs, tests/time.rs
Time offset can only appear after time or timezone. For example, the following formats are valid:
```
02:25 +01:00
UTC +01:00
```
And the following formats are invalid:
```
2025-05-19 +01:00
9:04:30 PM +0530
```
This PR also removes some invalid tests.
=> fix: time offset can only appear after time or timezone

src/items/date.rs, src/items/mod.rs, src/items/year.rs
=> feat: add a year module

src/items/builder.rs, src/items/mod.rs
The old logic is problematic: it resets the value of the `dt` variable at each iteration of the relative item processing. We fix it by moving the base datetime truncating logic to the start of the `build()` method.
After this fix gets merged, we can close #131.
=> fix base datetime handling in the builder

tests/common/mod.rs
Fixes the issue I mentioned in https://github.com/uutils/parse_datetime/pull/161#issuecomment-2999980201
=> tests: set timezone to `UTC0` in integration tests

src/items/time.rs
This PR changes the return value of a private function from `Option<Offset>` to just `Offset` because the function never returns `None`.
=> chore: remove unnecessary `Option` as return value

src/items/builder.rs, src/items/mod.rs, src/items/pure.rs, src/items/time.rs, src/items/year.rs
Implement GNU-compatible pure number interpretation that treats pure number as year or time based on the current parsing context.
Closes #197.
=> feat: implement pure number parsing

src/items/builder.rs, src/items/combined.rs, src/items/epoch.rs, src/items/mod.rs, src/items/primitive.rs, src/items/time.rs
Replace f64-based timestamp and second parsing with structured types using separate second and nanosecond fields to eliminate floating-point precision issues.
=> refactor: replace floating-point seconds with precise integer representation

Cargo.lock, Cargo.toml, src/items/builder.rs, src/items/date.rs, src/items/year.rs
And added a function to convert `Date` to `jiff::civil::Date`.
=> (jiff series #1) refactor: add jiff and optimize date type sizes

src/items/timezone.rs
This PR renames the function `tzname_to_offset` to `timezone_name_to_offset` to be consistent with other function names in the file that all use `timezone` instead of `tz`. And it renames `newtz` to `new_tz` to be consistent with another variable in the same function named `other_tz`.
=> refactor: rename a function name and a var name

Cargo.lock, Cargo.toml
As the switch from `chrono` to `jiff` is done, I think it's time for a new release.
=> Bump version to `0.12.0`

src/items/date.rs, tests/time.rs
This PR purposes changes that fix uutils/coreutils#8754 after a chore in coreutils to move from parse_datetime v0.11.0 to the latest including this fix.
Summary:
- Replaced `ErrMode::Cut(e)` with `ErrMode::BackTrack(e)` within date items parser functions to enable alternate parser flow to continue instead of failing prematurely.
Details:
- When using `ErrMode::Cut(e)` within a parser it signals that the error is not recoverable and the parser chain unwinds and fails. In some cases this is desirable but for the parser functions in date it seems they are recoverable errors.
- https://docs.rs/winnow/0.7.13/winnow/error/enum.ErrMode.html#variant.Backtrack
- https://docs.rs/winnow/0.7.13/winnow/error/enum.ErrMode.html#variant.Cut
Testing notes:
- New tests have been added to confirm parsing of …
=> Changing ErrMode::Cut to ErrMode::Backtrack to allow alt parser flow (Fix for uutils/coreutils issue 8754)
